# Generated by Django 6.0.5 on 2026-07-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cmms_equipment_supplier_id",
                    models.IntegerField(
                        blank=True, db_column="CMMS_EquipmentSupplierID", null=True
                    ),
                ),
                (
                    "supplier_manufacturer",
                    models.IntegerField(
                        blank=True, db_column="SupplierManufacturer", null=True
                    ),
                ),
                ("active", models.BooleanField(db_column="Active", default=True)),
                (
                    "universal_id_t_equipment_supplier",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_T_EquipmentSupplier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "universal_id_m_supplier",
                    models.CharField(
                        blank=True,
                        db_column="Universal_ID_M_Supplier",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        db_column="EquipmentID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_suppliers",
                        to="master.equipmentmaster",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_column="SupplierID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_suppliers",
                        to="master.suppliermaster",
                    ),
                ),
            ],
            options={
                "db_table": "T_EquipmentSupplier",
            },
        ),
    ]
