# Generated by Django 6.0.5 on 2026-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrationservices", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="EquipmentSupplier",
                ),
            ],
            database_operations=[],
        )
    ]
